### ISSUE TITLE
pp

### ISSUE THREAD

**Issue by arlgnv** [Inontran/hotel-toxin#18]
Остальное сам проверь
![image](https://user-images.githubusercontent.com/46949445/130465524-76ee0529-cb0d-4337-b038-70120ba40982.png)

**Comment by arlgnv** [comment]
По макету высота этой части 830px, а у тебя 509px. Почему?
![image](https://user-images.githubusercontent.com/46949445/133222989-1fe82a04-47d9-448d-952e-3650b13d4762.png)

**Comment by Inontran** [comment]
Потому что первый экран вместе с шапкой сайта чаще всего делают высотой 100vh.

**Comment by Inontran** [comment]
> По макету высота этой части 830px, а у тебя 509px. Почему?
> ![image](https://user-images.githubusercontent.com/46949445/133222989-1fe82a04-47d9-448d-952e-3650b13d4762.png)

Потому что первый экран вместе с шапкой сайта чаще всего делают высотой 100vh.
